### ISSUE TITLE
Plan a database.

### ISSUE THREAD

**Issue by Nhawdge** [aliselmes/recipe-tracker#5]
This is a no-code challenge to make you think. This is probably one of the most critical steps in any project. As Linus Torvalds (creator of Linux and Git) once said: 
> Bad programmers worry about the code. Good programmers worry about data structures and their relationships

Databases work on a short heirarchy, Database name (Project level) -> Table (object level) -> Column (Property/attribute level).

Create the tables required for the recipe tracker database. This is an iterative process, feel free to create and add extra notations or questions. We'll talk through this in full at some point.

[Hint: hit edit to see markdown notation for tables](https://help.github.com/en/github/writing-on-github/organizing-information-with-tables)

**Table Name**
|Property name | Type|
|---|---|
Name | string
Name | bool
Name | number
Name | long string

**Comment by aliselmes** [comment]
Ok so I'm starting at the "1000 ft view" then working my way inwards...
The first table might contain all the recipes - something like:

**All Recipes**
|Property name | Type|
|---|---|
Recipe 1 | Object (an individual recipe)
Recipe 2 | Object



Then the table for each individual recipe might look like:

**Recipe**
|Property name | Type|
|---|---|
Recipe Name | String
Ingredients | Array of objects
Instructions | Array of objects

**Comment by aliselmes** [comment]
Then we would need an ingredient table - each ingredient would be an object:

**Ingredient**
|Property Name | Type|
|---|---|
Ingredient name | string
Amount | number
Measurement | string

**Comment by aliselmes** [comment]
Finally we would need an Instructions table - each list of instruction could be an object:

**Instruction**
|Property Name | Type|
|---|---|
Step | number e.g.  1
Details | long string e.g. a sentence describing the step

**Comment by aliselmes** [comment]
Have I gone about this the right way? My thinking is that if each instruction and ingredient is an object we can create an ingredients array and an instructions array as properties of each recipe. Then we can store each recipe object as a property of an "All Recipes" object.

I hope I am starting to fill in the "rest of the owl"...!

**Comment by Nhawdge** [comment]
Alright, so this is gonna be a long one. When I wrote the issue I didn't realize just how hard databasing is to teach. You're really close, frighteningly close to be honest. But there are a lot of database/SQL caveats that you need to handle and approach. I'd recommend watching a video on you tube or something about database normalization. 

You did a great job on figuring these out, but I'm gonna help ya and make a schema. **Your next task** is to make a database and create the following tables. We'll cover them on Friday so come with questions, or we'll tangent until we find something useful. 

Note: everything should be camelcase, no plurals, I'm clarifying in case I make mistakes 

**Recipes:** 
|Name|Type|Notes|
|---|---|---|
|id|varchar(36)|key|
|name|varchar(1000)|required|
|dateAdded|date|optional|
|author|varchar(1000)|optional|

**Ingredients:**
|Name|Type|Notes|
|---|---|---|
|id|varchar(36)|key|
|recipeId|varchar(36)|foreign key|
|name|varchar(1000)||
|amount|varchar(100)||
|measurement|varchar(100)||

**Instructions:** (Or whatever your heart desires)
|Name|Type|Notes|
|---|---|---|
|id|varchar(36)|key|
|recipeId|varchar(36)|foreign key|
|stepNumber|varchar(10)|auto increment|
|instructions|varchar(1000)||

This might be a little daunting but use MySQL workbench to give it a shot, if you get stuck we can always clean it up. 

Bonus points if you create the SQL for it too (use a tool or hand written, both count)

**Comment by aliselmes** [comment]
Ok I watched some videos on database normalization, it makes sense! I might need to print out a chart of all the "normal forms" to help me remember them!

 I think I also managed to create the three tabes in MySQL workbench - and maybe even assigned recipeId to be a foreign key...it would be great to check over them tomorrow...

My evenings this week are pretty hectic so I'm not sure I'll manage to get much more done unfortunately.

**Comment by Nhawdge** [comment]
That is A-Okay with me. We'll go over it on Friday. When you say tomorrow, do you mean you'll upload them to the repo so I can check them out or did you skip Wednesday?

**Comment by aliselmes** [comment]
Oops sorry I am a day ahead of myself...I meant go over them on Friday!

**Comment by Nhawdge** [comment]
Great work today! I'm considering this done.
